---
- set_fact:
    postgres_secrets: "{{ postgres_secrets | to_json }}"
    postgres_slave_secrets: "{{ postgres_slave_secrets | to_json }}"

- include: "{{role_path}}/../k8s-common/tasks/common.yml"
  vars:
    k8s_manifests_dir: '{{postgres_manifests_dir}}'
    k8s_resources: '{{postgres_resources}}'
    k8s_namespace: "{{ postgres_namespace | default('default') }}"
    k8s_shards: "{{ postgres_slave_shards }}"
