apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ postgres.name }}-{{ appname }}
  namespace: {{ postgres.namespace|default('default') }}
  labels: {{ postgres.labels }}
spec:
  replicas: {{ postgres.replicas|default(1) }}
  selector: {{ postgres.selector|default(postgres.labels) }}
  template:
    metadata:
      labels: {{ postgres.labels }}
    spec:
{% for container in postgres.containers %}
      containers:
      - name: {{ container.name }}
        image: {{ container.image }}
        resources:
{% if container.limits is defined %}
          limits:
{% if container.limits.cpu is defined %}
            cpu: {{ container.limits.cpu }}
{% endif %}
{% if container.limits.memory is defined %}
            memory: {{ container.limits.memory }}
{% endif %}
{% endif %}
{% if container.env is defined %}
        env:
{% for env in container.env %}
          - name: {{ env.name }}
            value: {{ env.value }}
{% endfor %}
{% endif %}
{% if container.command is defined %}
        command: {{ container.command }}
{% endif %}
{% if container.args is defined %}
        args: {{ container.args }}
{% endif %}
{% if container.volumeMounts is defined %}
        volumeMounts: {{ container.volumeMounts }}
{% endif %}
{% if container.ports is defined %}
        ports: {{ container.ports }}
{% endif %}
{% if container.livenessProbe is defined %}
        livenessProbe: {{ container.livenessProbe }}
{% endif %}
{% if container.readinessProbe is defined %}
        readinessProbe: {{ container.readinessProbe }}
{% endif %}
{% endfor %}
{% if postgres.volumes is defined %}
      volumes: {{ postgres.volumes }}
{% endif %}
{% if postgres.nodeSelector %}
      nodeSelector: {{ postgres.nodeSelector }}
{% endif %}
