apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ postgres.name }}-{{ appname }}
  namespace: {{ postgres.namespace|default('default') }}
  labels: {{ postgres.labels }}
spec:
{% if postgres.type is defined %}
  type: {{ postgres.type }} 
{% endif %}
  selector: {{ postgres.selector|default(postgres.labels) }}
{% if postgres.clusterIP is defined %}
  clusterIP:  {{ postgres.clusterIP }}
{% endif %}
  ports: 
    - name: pg
      port: 5432
      targetPort: 5432
