apiVersion: v1
kind: Secret
metadata:
  name: {{ postgres_slave_secrets.name }}
type: {{ postgres_slave_secrets.type }}
data:
{% if postgres_user is defined %}
  "postgres-user": "{{ postgres_user|default('postgres') | b64encode }}"
{% endif %}
{% if postgres_password is defined %}
  "postgres-password": "{{ postgres_password | b64encode }}"
{% endif %}
{% if replication.user is defined %}
  "repl-user": "{{ replication.user | default('replicator') | b64encode }}"
{% endif %}
{% if replication.password is defined %}
  "repl-password": "{{ replication.password | b64encode }}"
{% endif %}
{% if replication.master_host is defined %}
  "master-host": "{{ replication.master_host | b64encode }}"
{% endif %}
  "postgresql.conf": "{{lookup('template', role_path ~ '/templates/config/postgresqlslave.conf') |b64encode}}"
  "pghba.conf": "{{lookup('template',  role_path ~ '/templates/config/pghba.conf') |b64encode}}"
  "recovery.conf": "{{lookup('template', role_path ~ '/templates/config/recovery.conf') |b64encode}}"
