apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ postgres.name }}
  labels: {{ postgres_labels }}
spec:
  replicas: {{ postgres.replicas|default(1) }}
  selector: {{ postgres_selector|default(postgres_labels) }}
  template:
    metadata:
      labels: {{ postgres_labels }}
    spec:
      containers:
      - name: postgres
        image: "{{ postgres_container_image.name }}:{{ postgres_container_image.tag|default('latest') }}"
{%      if postgres_container_limits is defined %}
        resources:
          limits:
{%        if postgres_container_limits.cpu is defined %}
            cpu: {{ postgres_container_limits.cpu }}
{%        endif %}
{%        if postgres_container_limits.memory is defined %}
            memory: {{ postgres_container_limits.memory }}
{%        endif %}
{%      endif %}
{%      if postgres_container_env is defined %}
        env:
{%        for env in postgres_container_env %}
          - name: {{ env.name }}
            value: {{ env.value }}
{%        endfor %}
{%      endif %}
{%      if postgres_container_command is defined %}
        command: {{ postgres_container_command }}
{%      endif %}
{%      if postgres_container_args is defined %}
        args: {{ postgres_container_args }}
{%      endif %}
{% if postgres_container_volumemounts is defined %}
        volumeMounts: {{ postgres_container_volumemounts }}
{% endif %}
{% if postgres_container_ports is defined %}
        ports: {{ postgres_container_ports }}
{% endif %}
{% if postgres_container_livenessprobe is defined %}
        livenessProbe: {{ postgres_container_livenessprobe }}
{% endif %}
{% if postgres_container_readinessprobe is defined %}
        readinessProbe: {{ postgres_container_readinessprobe }}
{% endif %}
{% if postgres_volumes is defined %}
      volumes: {{ postgres_volumes|to_json }}
{% endif %}
{% if postgres_nodeselector is defined %}
      nodeSelector: {{ postgres_nodeselector }}
{% endif %}
      nodeName: "{{ postgres_nodeName }}"
